apiVersion: v1
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/master/images/java.png
name: spring-cloud-k8s-minion
version: 0.1.0-SNAPSHOT
